services:
  backend:
    image: ${BACKEND_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
