# Workflow for checking that test and build the branch code
name: Branch Verification

on:
  # Triggers the workflow on push events for all branches other than the "main" branch
  push:
    branches-ignore:
      - "main"

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: keken-backend-image

jobs:
  test:
    runs-on: ubuntu-latest
    # Set a timeout in case something get stuck or hang in the tests
    timeout-minutes: 5
    steps:
      # Get the code from the repository unto the machine
      - name: Fetch code
        uses: actions/checkout@v4

      # Install dependencies in backend folder
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      # Create .env file for the test job in backend folder
      - name: Create backend testing env file
        run: echo "${{ secrets.TEST_JOB_ENV }}" > ./.env
        working-directory: ./backend

      # Run backend tests in backend folder
      - name: Run backend tests
        run: npm test
        working-directory: ./backend
